import 'dart:async';

import 'app_link_data.dart';
import 'app_link_handler.dart';
import 'app_link_parameters.dart';
import 'app_link_resolver.dart';
import 'app_link_source.dart';
import 'app_link_source_type.dart';
import 'app_links_source.dart';
import 'dynamic_app_links_configuration.dart';
import 'dynamic_app_links_exception.dart';
import 'link_deduplicator.dart';
import 'link_handling_result.dart';
import 'short_link_parameters.dart';
import 'short_link_provider.dart';
import 'short_link_result.dart';

/// Receives App Links, builds canonical links, creates short links, and
/// optionally delegates in-app navigation to an application callback.
///
/// Create this class early in application startup, then either listen to
/// [onLink] yourself or call [startListening] to invoke the configured
/// [AppLinkHandler] automatically.
final class DynamicAppLinks {
  /// Creates a Dynamic App Links facade.
  DynamicAppLinks({
    AppLinkSource? source,
    AppLinkResolver resolver = const PassthroughAppLinkResolver(),
    ShortLinkProvider? shortLinkProvider,
    AppLinkHandler? handler,
    DynamicAppLinksConfiguration configuration =
        const DynamicAppLinksConfiguration(),
  })  : _source = source ?? AppLinksSource(),
        _resolver = resolver,
        _shortLinkProvider = shortLinkProvider,
        _handler = handler,
        _allowedSchemes = configuration.allowedSchemes
            .map((scheme) => scheme.toLowerCase())
            .toSet(),
        _allowedHosts = configuration.allowedHosts
            .map((host) => host.toLowerCase())
            .toSet(),
        _deduplicator = LinkDeduplicator(configuration.duplicateWindow) {
    if (configuration.duplicateWindow.isNegative) {
      throw ArgumentError.value(
        configuration.duplicateWindow,
        'configuration.duplicateWindow',
        'The duplicate window cannot be negative.',
      );
    }

    _linkController = StreamController<AppLinkData>.broadcast(
      onListen: () => unawaited(_ensureSourceStarted()),
    );
    _handlingResultController =
        StreamController<LinkHandlingResult>.broadcast();
  }

  final AppLinkSource _source;
  final AppLinkResolver _resolver;
  final ShortLinkProvider? _shortLinkProvider;
  final AppLinkHandler? _handler;
  final Set<String> _allowedSchemes;
  final Set<String> _allowedHosts;
  final LinkDeduplicator _deduplicator;

  late final StreamController<AppLinkData> _linkController;
  late final StreamController<LinkHandlingResult> _handlingResultController;

  StreamSubscription<Uri>? _sourceSubscription;
  StreamSubscription<AppLinkData>? _handlerSubscription;
  Future<AppLinkData?>? _initialLinkFuture;
  Future<void> _linkQueue = Future<void>.value();
  Future<void> _handlingQueue = Future<void>.value();
  bool _sourceStarted = false;
  bool _disposed = false;

  /// A unified, broadcast stream containing the initial link and later links.
  ///
  /// The initial Future and native stream are coordinated so the same resolved
  /// URI is emitted once inside [DynamicAppLinksConfiguration.duplicateWindow].
  Stream<AppLinkData> get onLink {
    _ensureNotDisposed();
    return _linkController.stream;
  }

  /// Emits outcomes generated by [startListening] and [handleLink].
  Stream<LinkHandlingResult> get onHandlingResult {
    _ensureNotDisposed();
    return _handlingResultController.stream;
  }

  /// Returns the validated and resolved link that launched the app.
  ///
  /// The native initial-link lookup is performed once and then cached.
  Future<AppLinkData?> getInitialLink() {
    _ensureNotDisposed();
    return _initialLinkFuture ??= _loadInitialLink();
  }

  /// Builds a canonical App Link without calling the backend.
  Uri buildLink(AppLinkParameters parameters) {
    _ensureNotDisposed();
    final uri = parameters.toUri();
    _validate(uri);
    return uri;
  }

  /// Creates a short link through the configured [ShortLinkProvider].
  Future<ShortLinkResult> buildShortLink(
    ShortLinkParameters parameters,
  ) async {
    _ensureNotDisposed();
    _validate(parameters.link);

    final provider = _shortLinkProvider;
    if (provider == null) {
      throw const ShortLinkProviderNotConfiguredException();
    }

    try {
      return await provider.createShortLink(parameters);
    } catch (error, stackTrace) {
      if (error is DynamicAppLinksException) {
        rethrow;
      }
      throw ShortLinkCreationException(
        'The configured backend could not create a short link.',
        cause: error,
        causeStackTrace: stackTrace,
      );
    }
  }

  /// Starts automatically passing [onLink] events to the configured handler.
  ///
  /// Calling this method more than once is safe. When no handler is configured,
  /// every event produces an ignored [LinkHandlingResult].
  Future<void> startListening() async {
    _ensureNotDisposed();
    if (_handlerSubscription != null) {
      return;
    }

    _handlerSubscription = onLink.listen(
      (link) {
        _handlingQueue = _handlingQueue.then((_) async {
          final result = await _handlePreparedLink(link);
          _addHandlingResult(result);
        });
      },
      onError: (Object error, StackTrace stackTrace) {
        _addHandlingResult(
          LinkHandlingResult.failed(
            error: error,
            stackTrace: stackTrace,
          ),
        );
      },
    );
  }

  /// Stops automatic navigation while keeping [onLink] available.
  Future<void> stopListening() async {
    await _handlerSubscription?.cancel();
    _handlerSubscription = null;
  }

  /// Validates, resolves, and handles a URI supplied by application code.
  Future<LinkHandlingResult> handleLink(Uri uri) async {
    _ensureNotDisposed();

    try {
      final link = await _prepareLink(uri, AppLinkSourceType.manual);
      final result = await _handlePreparedLink(link);
      _addHandlingResult(result);
      return result;
    } on InvalidAppLinkException catch (error, stackTrace) {
      final result = LinkHandlingResult.invalid(error, stackTrace);
      _addHandlingResult(result);
      return result;
    } on UntrustedAppLinkException catch (error, stackTrace) {
      final result = LinkHandlingResult.invalid(error, stackTrace);
      _addHandlingResult(result);
      return result;
    } catch (error, stackTrace) {
      final result = LinkHandlingResult.failed(
        error: error,
        stackTrace: stackTrace,
      );
      _addHandlingResult(result);
      return result;
    }
  }

  /// Releases native subscriptions and closes package streams.
  Future<void> dispose() async {
    if (_disposed) {
      return;
    }
    _disposed = true;

    await stopListening();
    await _sourceSubscription?.cancel();
    _sourceSubscription = null;
    await _linkQueue;
    await _handlingQueue;
    await _linkController.close();
    await _handlingResultController.close();
  }

  Future<void> _ensureSourceStarted() async {
    if (_sourceStarted || _disposed) {
      return;
    }
    _sourceStarted = true;

    _sourceSubscription = _source.onLink.listen(
      (uri) => _enqueueIncomingLink(uri, AppLinkSourceType.incoming),
      onError: (Object error, StackTrace stackTrace) {
        if (!_linkController.isClosed) {
          _linkController.addError(error, stackTrace);
        }
      },
    );

    try {
      final initialLink = await getInitialLink();
      if (initialLink != null) {
        _emitIfNew(initialLink);
      }
    } catch (error, stackTrace) {
      if (!_linkController.isClosed) {
        _linkController.addError(error, stackTrace);
      }
    }
  }

  Future<AppLinkData?> _loadInitialLink() async {
    final uri = await _source.getInitialLink();
    if (uri == null) {
      return null;
    }
    return _prepareLink(uri, AppLinkSourceType.initial);
  }

  void _enqueueIncomingLink(Uri uri, AppLinkSourceType source) {
    _linkQueue = _linkQueue.then((_) async {
      try {
        final link = await _prepareLink(uri, source);
        _emitIfNew(link);
      } catch (error, stackTrace) {
        if (!_linkController.isClosed) {
          _linkController.addError(error, stackTrace);
        }
      }
    });
  }

  Future<AppLinkData> _prepareLink(
    Uri originalUri,
    AppLinkSourceType source,
  ) async {
    _validate(originalUri);

    late final Uri resolvedUri;
    try {
      resolvedUri = await _resolver.resolve(originalUri);
    } catch (error, stackTrace) {
      throw AppLinkResolutionException(
        'The incoming App Link could not be resolved.',
        cause: error,
        causeStackTrace: stackTrace,
      );
    }

    _validate(resolvedUri);
    return AppLinkData(
      originalUri: originalUri,
      uri: resolvedUri,
      source: source,
      receivedAt: DateTime.now().toUtc(),
    );
  }

  void _emitIfNew(AppLinkData link) {
    if (_disposed || _linkController.isClosed) {
      return;
    }
    if (_deduplicator.isDuplicate(link.uri, link.receivedAt)) {
      return;
    }
    _linkController.add(link);
  }

  Future<LinkHandlingResult> _handlePreparedLink(AppLinkData link) async {
    final handler = _handler;
    if (handler == null) {
      return LinkHandlingResult.ignored(link);
    }

    try {
      final handled = await Future<bool>.sync(() => handler(link));
      return handled
          ? LinkHandlingResult.handled(link)
          : LinkHandlingResult.ignored(link);
    } catch (error, stackTrace) {
      return LinkHandlingResult.failed(
        link: link,
        error: error,
        stackTrace: stackTrace,
      );
    }
  }

  void _validate(Uri uri) {
    if (!uri.hasScheme) {
      throw InvalidAppLinkException('The App Link has no URI scheme: $uri');
    }

    final scheme = uri.scheme.toLowerCase();
    if (_allowedSchemes.isNotEmpty && !_allowedSchemes.contains(scheme)) {
      throw UntrustedAppLinkException(
        'The URI scheme "$scheme" is not allowed.',
      );
    }

    if ((scheme == 'http' || scheme == 'https') && uri.host.isEmpty) {
      throw InvalidAppLinkException('The web App Link has no host: $uri');
    }

    final host = uri.host.toLowerCase();
    if (_allowedHosts.isNotEmpty && !_allowedHosts.contains(host)) {
      throw UntrustedAppLinkException(
        'The URI host "$host" is not allowed.',
      );
    }
  }

  void _addHandlingResult(LinkHandlingResult result) {
    if (!_disposed && !_handlingResultController.isClosed) {
      _handlingResultController.add(result);
    }
  }

  void _ensureNotDisposed() {
    if (_disposed) {
      throw StateError('DynamicAppLinks has already been disposed.');
    }
  }
}
